### ISSUE TITLE
Partner Name Change update required

### ISSUE THREAD

**Issue by ACROSSHealth12** [openEHR/openehr-website#11]
On the page link below the Partner name 'Fivium' and link to Fivium.co.uk are listed. The company has restructured and now should be listed as ACROSS Health link www.acrosshealth.co.uk. Can you please make the update and remove links to fivium uk. 

http://www.marand-think.com/news-nhs2014

Thanks
Richard Turner
richard.turner@across.co.uk
Sales and Marketing Manager
ACROSS Health Limited

**Comment by freshehr** [comment]
Hi Richard,

This is just a link out to one of our Industry partners websites, it is not under the control of openEHR. I am sure Tomaž Gornik tomaz.gornik@marand.si , the Marand CEO would be happy to update the page, and any other promtional material that did include the Fivium name - suggest you contact Tomaž directly.

Ian

**Comment by ACROSSHealth12** [comment]
Hi Ian, ok great, thanks Richard
